apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amit-proj1
  namespace: argocd
spec:
  project: stage-devseccops
  source:
    repoURL: 'git@github.com:amitopenwriteup/nginx-argoproj.git'
    targetRevision: main
    path: dev
  destination:
    name: arn:aws:eks:ap-south-1:130705418859:cluster/stage-devseccops-eks-cluster
    namespace: stage-nginx-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
